/**
 * generated by Xtext 2.25.0
 */
package dk.sdu.mmmi.mdsd.math;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Function Call</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dk.sdu.mmmi.mdsd.math.FunctionCall#getExternalRef <em>External Ref</em>}</li>
 *   <li>{@link dk.sdu.mmmi.mdsd.math.FunctionCall#getArgs <em>Args</em>}</li>
 * </ul>
 *
 * @see dk.sdu.mmmi.mdsd.math.MathPackage#getFunctionCall()
 * @model
 * @generated
 */
public interface FunctionCall extends Expression
{
  /**
   * Returns the value of the '<em><b>External Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>External Ref</em>' reference.
   * @see #setExternalRef(ExternalDefinition)
   * @see dk.sdu.mmmi.mdsd.math.MathPackage#getFunctionCall_ExternalRef()
   * @model
   * @generated
   */
  ExternalDefinition getExternalRef();

  /**
   * Sets the value of the '{@link dk.sdu.mmmi.mdsd.math.FunctionCall#getExternalRef <em>External Ref</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>External Ref</em>' reference.
   * @see #getExternalRef()
   * @generated
   */
  void setExternalRef(ExternalDefinition value);

  /**
   * Returns the value of the '<em><b>Args</b></em>' containment reference list.
   * The list contents are of type {@link dk.sdu.mmmi.mdsd.math.Expression}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Args</em>' containment reference list.
   * @see dk.sdu.mmmi.mdsd.math.MathPackage#getFunctionCall_Args()
   * @model containment="true"
   * @generated
   */
  EList<Expression> getArgs();

} // FunctionCall
